name = "Alicorn"
uuid = "80a53053-bcf5-42c0-89b5-2140b4d6711b"
authors = ["Daniel Hümmer <daniel.huemmer@gmx.com> and contributors"]
version = "0.2.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
